# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TopopyTools
                                 A QGIS plugin
 This plugin analyzes drainage networks and related metrics
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-11-12
        copyright            : (C) 2020 by J. Vicente Pérez / UGR
        email                : vperez@ugr.es
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'J. Vicente Pérez / UGR'
__date__ = '2020-11-12'
__copyright__ = '(C) 2020 by J. Vicente Pérez / UGR'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TopopyTools class from file TopopyTools.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .topopy_tools import TopopyToolsPlugin
    return TopopyToolsPlugin()
